name: first Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "Hello World"
      - name: print hello world again
        run: echo "Hello World Again"
      - name: print hello world one more time
        run: echo "Hello World One More Time"  
