name: second workflow
on: workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter
        run: echo "Running linter..."
jobs:
  test:
    needs: lint
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run tests
          run: echo "Running tests..."
jobs:
  build:
    needs: test
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Build project
          run: echo "Building project..."    
